name: Build Local AI (Open AI API) Container
on:
  push:
    branches:
    - main
    paths:
    - 'llm-docker/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
         
    - name: Log in to the Github Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker file
      run: |
        docker build -t ghcr.io/{{ github.actor }}/bionicgpt-model-api:latest -f llm-docker/Dockerfile.localai llm-docker
        docker push ghcr.io/{{ github.actor }}/bionicgpt-model-api